kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: chrishsieh/drone_pipeline_wait
    dockerfile: ./Dockerfile
    context: ./
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
      - latest